### ISSUE TITLE
[RFE] Should give option to select storageclass

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#111]
Though there are no option at the moment to select anything related to storage, but when implemented, it should have option to select the storageclass as well available on the cluster

**Comment by pkliczewski** [comment]
We are not handling storage in the provider and we have this [card](https://trello.com/c/QPoUqJVw/65-model-storage-2-weeks) to track it. ATM we rely on default `storageclass`.

**Comment by pkliczewski** [comment]
We are not going to work on it if anything changes we will reopen this issue.
