### ISSUE TITLE
Unable to Power ON/OFF VM

### ISSUE THREAD

**Issue by Dhamo1107** [ManageIQ/manageiq-providers-kubevirt#261]
Hi,

I am using ManageIQ Quinteros version. I added an OpenShift provider under "Containers Providers" and configured KubeVirt details in the "Virtualization" tab, successfully connecting both OpenShift and KubeVirt in ManageIQ.

When I navigate to the VM list page of the infrastructure provider, I see a VM listed. However, I am unable to start or stop the VM using ManageIQ. I expected the VM to power on or off successfully from ManageIQ.

Notably, when I perform power operations (start/stop) directly in the Red Hat OpenShift platform, the power status of the VM is correctly reflected in ManageIQ.

Steps to Reproduce:
Navigate to the "Infrastructure Provider" VM list page and locate the listed VM.
Attempt to start or stop the VM using ManageIQ.

Observe the error in the logs and that the power operation does not succeed.
![image](https://github.com/user-attachments/assets/895c9302-d15f-46f2-bb15-d76def672dc3)
![image](https://github.com/user-attachments/assets/a45859e7-0132-4705-a64b-c2ee5c7bd29a)

The URL being generated for retrieving VM details is: `GET https://console-openshift-console.apps.ocp4.xaasio.int:6443/apis/kubevirt.io/v1/virtualmachines/centos-stream9-cyan-silkworm-83`

However, the correct URL to start the VM (which was successfully tested) is: `PUT https://console-openshift-console.apps.ocp4.xaasio.int:6443/apis/subresources.kubevirt.io/v1/namespaces/default/virtualmachines/centos-stream9-cyan-silkworm-83/start`

If the subresources is removed from the URL, the following error occurs:
`{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "virtualmachines.kubevirt.io \"centos-stream9-cyan-silkworm-83\" not found",
  "reason": "NotFound",
  "details": {
    "name": "centos-stream9-cyan-silkworm-83",
    "group": "kubevirt.io",
    "kind": "virtualmachines"
  },
  "code": 404`

I believe there might be issues with the subresources and namespace. How can I debug and fix this?

Relevant Gems:
- fog-kubevirt 1.4.0

Thanks for your help and insights!

**Comment by Fryguy** [comment]
@nasark Can you take a look at this bug?

**Comment by agrare** [comment]
I suspect this will be fixed by https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/249

**Comment by Dhamo1107** [comment]
Thank You @agrare & @Fryguy, #249 Fixed the issue
