### ISSUE TITLE
Wrongly shown valid auth tick

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#35]
After adding an OpenShift as a Container provider & KubeVirt for Virtualization, if the token was valid, but with different role/access, and the ManageIQ cannot refresh/fetch data from the provider, it still shows the green tick.
This is not fully a bug, as the token might be valid, but if the provider is not able to fetch the exact or any details with that token, then it does not make sense to make that auth a green tick.
![screenshot from 2018-02-28 14-20-50](https://user-images.githubusercontent.com/6758282/36778696-8d24074e-1c93-11e8-8873-1e752509766c.png)
![screenshot from 2018-02-28 14-21-17](https://user-images.githubusercontent.com/6758282/36778701-8e3a11aa-1c93-11e8-95d9-ba3d455dd145.png)

**Comment by vatsalparekh** [comment]
@masayag @pkliczewski

**Comment by masayag** [comment]
@vatsalparekh so the problem is with the kubevirt provider or with openshift provider or both ?

**Comment by pkliczewski** [comment]
@vatsalparekh will you have time to check it?

**Comment by pkliczewski** [comment]
This issue is tracked by this [card](https://trello.com/c/KSykrsEp/74-5-wrongly-shown-valid-auth-tick)

**Comment by vatsalparekh** [comment]
@masayag @pkliczewski so I see that error when adding openshift provider
for kubevirt, refresh status is not working right now, but its happening with just openshift also

**Comment by pkliczewski** [comment]
@masayag Is there enough information to try to reproduce it?

**Comment by masayag** [comment]
The kubevirt's auth_tick status will be solved by https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/259

**Comment by masayag** [comment]
@pkliczewski The reason for the specific issue is the assumption that with the provided token, the user can access the virtualization resource.
However, https://github.com/fog/fog-kubevirt/blob/master/lib/fog/compute/kubevirt.rb#L164 only verifies the existence of the kubevirt apis, not the ability of the user to use those.

We can either add an attempt to access the vms or postpone this till supporting authorization on kubevirt properly.

**Comment by pkliczewski** [comment]
@masayag What about triggering refresh?

**Comment by masayag** [comment]
@pkliczewski I'm not sure I followed your question. Did you mean triggering a refresh during connectivity check ?

**Comment by pkliczewski** [comment]
@masayag You mentioned

> We can either add an attempt to access the vms or postpone this till supporting authorization on kubevirt properly.

We could trigger a refresh instead and MIQ should update provider state with correct info,

**Comment by pkliczewski** [comment]
@masayag @vatsalparekh I miss understood the context. After having a conversation about it we decided not to handle it and update the release notes with this specific behavior. Once this [card](https://trello.com/c/vK22rUyw/63-8-rbac-for-kubevirt-provider) is fixed we will make sure it works correctly.
