### ISSUE TITLE
Extra buttons

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#36]
On `Add new Provider` and `Edit Provider`, these 2 extra buttons are there
![ezgif-2-09e96182a0](https://user-images.githubusercontent.com/6758282/36783275-8c8d5412-1ca1-11e8-84cb-7fbe919957d2.gif)

**Comment by vatsalparekh** [comment]
@masayag

**Comment by masayag** [comment]
closed, will be tracked on manageiq-ui-classic repo.
