### ISSUE TITLE
Manual refresh of the infra provider doesn't update anything

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#39]
When doing the manual refresh for the infra provider added from KubeVirt virtualization on OpenShift container provider, the refresh gives no error but the data is not updated in the miq.
@pkliczewski found that this could be due to the missing `cpu` spec in the `testvm` that was created on openshift side.
So we need to be more flexible in parsing the specs

**Comment by pkliczewski** [comment]
@vatsalparekh I checked your environment and I noticed that vm and templates were create in wrong namespace `myproject` whereas should be created in `default` namespace. We do not support different namespaces than `default`. I see that vm and templates are correctly refreshed in your environment.

**Comment by vatsalparekh** [comment]
@pkliczewski thanks for debugging that! I'm not seeing the VMs and templates as expected, closing this issue.
