### ISSUE TITLE
Targeted refresh for VMs created on Openshift shows error

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#47]
When doing a targeted refresh for a VM that was created directly on OpenShift and not via miq, shows the error in the Last refresh pane
```
Error - Less Than A Minute Ago
--
HTTP status code 404, offlinevirtualmachines.kubevirt.io "testvm-sata" not found
```

**Comment by masayag** [comment]
@vatsalparekh how did you create the vm ? 
Could you specify the steps for reproducing this issue (even attach the file used to create the vm)

**Comment by masayag** [comment]
Closed as duplicate of https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/47
The lack of support in target causes both issue and will be addressed by https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/52
