### ISSUE TITLE
Add better error message

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#49]
When going to add a new provider, if a user session has expired, rather then taking out to the login page, it keeps giving the error
```Something went wrong, please check the logs for more information.```
Message here is confusing as you won't find anything wrong in the log

**Comment by masayag** [comment]
@vatsalparekh this sounds like a general MIQ behavior, seems like this should be brought up in the manageiq-ui-classic repo rather here.

**Comment by vatsalparekh** [comment]
@masayag https://github.com/ManageIQ/manageiq-ui-classic/issues/3672
