### ISSUE TITLE
VM retirement notification

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#50]
When retiring a VM on KubeVirt, I am seeing sometimes the VM name is not populated, though this is not consistent, only seeing it sometimes
![screenshot from 2018-03-14 16-47-53](https://user-images.githubusercontent.com/6758282/37399610-1f491ed8-27a8-11e8-97ab-be6feb4930ff.png)

**Comment by masayag** [comment]
As I can see, the problem concerns additional flows, so it seems like we're missing a representational name for kubevirt's vm:

![selection_449](https://user-images.githubusercontent.com/316242/37763344-7014b4ce-2dc7-11e8-80f9-3cd06ead6049.png)

**Comment by masayag** [comment]
Fixed by https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/54
