### ISSUE TITLE
VMs not getting retired

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#57]
>KubeVirt version: 0.4
Manageiq: Version master.20180406233346_c9e7f02

Retiring VMs from ManageIQ shows them retired, but they're not actually deleted on the kubevirt side

![screenshot from 2018-04-11 17-18-54](https://user-images.githubusercontent.com/6758282/38615242-9892e4d4-3dad-11e8-8ade-1652575bc25d.png)
![screenshot from 2018-04-11 17-16-56](https://user-images.githubusercontent.com/6758282/38615243-98bc2a2e-3dad-11e8-802d-c929905f2763.png)

**Comment by vatsalparekh** [comment]
And when on a new appliance we add this provider, all the VMs come up as Powered On
![screenshot from 2018-04-11 17-32-39](https://user-images.githubusercontent.com/6758282/38615478-740202de-3dae-11e8-9200-88fbcb53ac69.png)

**Comment by masayag** [comment]
@vatsalparekh I've tested and debugged the flow and noticed that it is working as expected on kubevirt's master.

Please re-test it on latest kubevirt version, since I was able to retire running (live) and stopped (offline) vms which were both removed from kubevirt side.

**Comment by vatsalparekh** [comment]
Tested this issue on kubevirt `0.4.1` with `master` of provider, and it seems to be working @masayag @pkliczewski
