### ISSUE TITLE
Gap in Power state of a VM

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#69]
Unlike the traditional providers, Kubevirt has VM scheduling like Kubernetes way, means VMs would have phases like `Scheduling`, `Scheduled`,  `Pending`, or `Failed` in some cases.
The gap here is, even if the VM scheduling is failed, but it stays in `vms`, so in miq we see it as `Powered On` but that's not powered on actually. Or even `Scheduling` is like booting up for traditional vm, but here we just see it as `Powered on`, which is actually not the actual state.

**Comment by vatsalparekh** [comment]
this seems like current gap for miq, but maybe can be a gap for all the integrations using KubeVirt as a VM provider.
@pkliczewski @fabiand your inputs?

**Comment by pkliczewski** [comment]
@vatsalparekh Very good point. There are two potential solutions for this issue:

- Map kubevirt states to those defined in MIQ
- Add kubevirt specific states to MIQ

@agrare With which one we should go?

**Comment by agrare** [comment]
@pkliczewski I think we should have the real values in the raw_power_state column but map to traditional VM power states for consistency with the rest of the infra/cloud providers as well as we already have icons to represent these states.

**Comment by pkliczewski** [comment]
@agrare Thank you! Will use the approach you suggested.

**Comment by vatsalparekh** [comment]
@pkliczewski Seeing one more gap that sometimes the power state of the VM differ the actual state on the provider, but working on this issue would fix it

**Comment by pkliczewski** [comment]
PR solving it was merged
