### ISSUE TITLE
Correct virtualization token shows error in authentication

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#72]
For a existing provider, when the token for both default and virtualization was changed, and we just edit the token for virtualization, the authentication status for virtualization shows `!` but functions (like provisioning VMs) are working.
![screenshot from 2018-05-14 18-21-38](https://user-images.githubusercontent.com/6758282/39998483-d9a3526e-57a3-11e8-9640-6ab6fc865faf.png)

**Comment by vatsalparekh** [comment]
@miq-bot add-label bug

**Comment by vatsalparekh** [comment]
@masayag still seeing this on latest master
![screenshot from 2018-05-31 12-04-07](https://user-images.githubusercontent.com/6758282/40765673-dbc4afe6-64ca-11e8-9c50-4d60f281b3e0.png)

**Comment by masayag** [comment]
The error status is expected to remain until the refresh will be completed successfully.
Could you confirm that 'refresh' works correctly ? AFAICT, the token for openshift should be valid in order to complete the refresh.

**Comment by pkliczewski** [comment]
@masayag Is this consistent behavior with other providers or do they trigger refresh?

**Comment by masayag** [comment]
@pkliczewski should be common to all providers:

https://github.com/ManageIQ/manageiq/blob/master/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb#L38

**Comment by pkliczewski** [comment]
Closing as we agreed that proposed solution is correct
