### ISSUE TITLE
Cannot edit the default or virtualization endpoint alone

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#76]
When an administrator wants to change just one token, validation for both seem to be required (when editing the container provider)
> This is when the token for default is not valid anymore

![screenshot from 2018-05-21 12-26-13](https://user-images.githubusercontent.com/6758282/40294443-3b929bd4-5cf3-11e8-8721-88732d9ae8a3.png)

**Comment by cben** [comment]
I _think_ this is standard in manageiq providers UI — any invalid endpoint disables [Save] button.
