### ISSUE TITLE
Duplicate templates in service catalog

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#79]
There's just one template on provider, and seeing the same one in Infra->VM, but when making a service catalog it shows 2 template of the same name

![screenshot from 2018-05-22 19-18-00](https://user-images.githubusercontent.com/6758282/40367011-10aa094e-5df6-11e8-98ea-4ef17e1bbaef.png)

**Comment by pkliczewski** [comment]
ATM we haven't decided to support service catalog
