### ISSUE TITLE
Power state not shown in all vm page

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#84]
With the enhancement of #82 , I can see the expected power state in VM detail page
![screenshot from 2018-05-30 12-24-38](https://user-images.githubusercontent.com/6758282/40703985-9200ce42-6404-11e8-99f7-33a21d4227d2.png)
But, the all VM page doesn't show these **new** states
![screenshot from 2018-05-30 12-22-56](https://user-images.githubusercontent.com/6758282/40704068-ccefe6f0-6404-11e8-9ba9-ca7727ffce31.png)

**Comment by pkliczewski** [comment]
@agrare I followed [this](https://github.com/ManageIQ/manageiq-providers-vmware/blob/master/app/models/manageiq/providers/vmware/cloud_manager/vm.rb#L23) code to update `raw_power_state` which you can find [here](https://github.com/ManageIQ/manageiq-providers-kubevirt/blob/master/app/models/manageiq/providers/kubevirt/infra_manager/vm.rb#L22) but it seems that `powering_up` is missing an icon. I can see it in detail view but not in general view. Do you know what am I missing?

**Comment by agrare** [comment]
@pkliczewski I'm not sure, there is an icon for it in ui-classic `./manageiq-ui-classic/app/assets/images/svg/currentstate-powering_up.svg`

**Comment by himdel** [comment]
@pkliczewski You need to add the new state to the `MACHINE_STATE_QUADRANT` hash in `QuadiconHelper`: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/helpers/quadicon_helper.rb#L9

**Comment by pkliczewski** [comment]
@himdel Those states are not new. All of them are used either by aws, vmware or both providers. @agrare  gave a link to https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/assets/images/svg/currentstate-powering-up.svg so hopefully I won't add new svg. 

Thanks for pointing me to `quadicon_helper`.

**Comment by himdel** [comment]
@miq-bot close_issue

the PR is merged now :)
