### ISSUE TITLE
Kubernetes ovm name validation change

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#85]
With issue https://github.com/kubevirt/kubevirt/issues/1092 , kubevirt should be updated to not allow creation VM with unsupported name format

**Comment by pkliczewski** [comment]
Vm/ovm naming needs to be align with `DNS-1123`. In import vm we use [this](https://github.com/ansibleplaybookbundle/import-vm-apb/blob/master/bin/job#L65) approach.
